# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prenovi', '0004_contractor_workinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinstance',
            name='client_name',
            field=models.CharField(default='Enter Client Name', max_length=100),
        ),
        migrations.AddField(
            model_name='workinstance',
            name='summary',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workinstance',
            name='title',
            field=models.CharField(default=models.CharField(default='Enter Client Name', max_length=100), help_text='Name of the project', max_length=100),
        ),
        migrations.AlterField(
            model_name='workinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular workinstance  across whole Database', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workinstance',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 12, 3, 7, 616478)),
        ),
    ]
