# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenovi', '0005_auto_20170730_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinstance',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 12, 10, 0, 761847)),
        ),
        migrations.AlterField(
            model_name='workinstance',
            name='title',
            field=models.CharField(blank=True, help_text='Name of the project', max_length=100),
        ),
    ]
