# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenovi', '0008_auto_20170730_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinstance',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 12, 18, 44, 476200)),
        ),
    ]
