# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenovi', '0011_auto_20170730_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinstance',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 38, 49, 26161)),
        ),
    ]
